[build]
  command = "pnpm run build"
  publish = "dist"  # or "build", depending on your setup

[build.environment]
  NODE_VERSION = "18"  # Specify your Node.js version if required

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
